services:
  postgres:
    image: postgres:15-alpine
    container_name: eventory_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventory_network

volumes:
  postgres_data:
    driver: local

networks:
  eventory_network:
    driver: bridge